# Generated by Django 4.2 on 2023-05-02 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=64, verbose_name="Nome do Serviço"),
                ),
                ("smalldesc", models.TextField(verbose_name="Descrição curta")),
                ("largedesc", models.TextField(verbose_name="Descrição longa")),
                (
                    "icon",
                    models.FileField(
                        help_text="O arquivo necessita ser do tipo SVG.",
                        upload_to="services/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["svg"])
                        ],
                        verbose_name="Ícone do Serviço",
                    ),
                ),
            ],
        ),
    ]
